name: Python CI

# Trigger
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Job
jobs:
  test_scrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Setup Python Env
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest